import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, stat, utimes, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { MemoryTranslationService, parseTranslation } from "./memory-translation.js";
import { buildNativeMemoryView, cleanMemoryLine, detectMemoryLanguage, parseNativeMemorySummary } from "./native-memory-view.js";
import { PortalMemoryService } from "./portal-memory-service.js";
import {
  USER_MEMORY_SECTION_START,
  composeMemorySummary,
  readUserMemories,
  syncAgentStudioMemoryProjection,
  userMemoryStoreDir
} from "./user-memory.js";

const NATIVE_SUMMARY = [
  "## User Profile",
  "",
  "The user is a product manager who works on LTE base stations.",
  "",
  "## User preferences",
  "",
  "- Prefers answers in Chinese with the conclusion first.",
  "  - Uses tables for comparisons.",
  "- [ad-hoc note] Wants DingTalk summaries short",
  "- See /usr/local/agent-studio/agent-api/temp/codex-homes/x/memories/rollout_summaries/a.md",
  "",
  "## General Tips",
  "",
  "- Check OMC alarms before restarting cells.",
  "",
  "## What's in Memory",
  "",
  "### Older Memory Topics",
  "",
  "#### 2026-09-01",
  "- rollout_summaries/2026-09-01.md",
  ""
].join("\n");

const LEGACY_PLACEHOLDER = "# Memory Summary\n\nGenerated by Agent Studio MemoryEngine. Codex reads this alongside native memory files.\n\nNo consolidated memories yet.\n";

describe("user memory projection", () => {
  it("prepends a managed user section and keeps Codex's own summary intact", () => {
    const items = [{ id: "1", text: "回答用中文", createdAt: "2026-10-01T00:00:00Z", updatedAt: "2026-10-01T00:00:00Z" }];
    const composed = composeMemorySummary(NATIVE_SUMMARY, items);
    expect(composed.startsWith(USER_MEMORY_SECTION_START)).toBe(true);
    expect(composed).toContain("- 回答用中文");
    expect(composed).toContain(NATIVE_SUMMARY.trim());
    // Idempotent, and removing every item restores Codex's summary.
    expect(composeMemorySummary(composed, items)).toBe(composed);
    expect(composeMemorySummary(composed, [])).toBe(`${NATIVE_SUMMARY.trim()}\n`);
    // Untouched when there is nothing of ours.
    expect(composeMemorySummary(NATIVE_SUMMARY, [])).toBe(NATIVE_SUMMARY);
    // Legacy Agent Studio placeholders count as empty.
    expect(composeMemorySummary(LEGACY_PLACEHOLDER, [])).toBe("");
  });
});

describe("native memory view", () => {
  it("shows profile, preferences and tips only, without Codex bookkeeping", () => {
    expect(parseNativeMemorySummary(NATIVE_SUMMARY)).toEqual({
      profile: ["The user is a product manager who works on LTE base stations."],
      preferences: [
        { text: "Prefers answers in Chinese with the conclusion first.", details: ["Uses tables for comparisons."] },
        { text: "Wants DingTalk summaries short", details: [] }
      ],
      tips: [{ text: "Check OMC alarms before restarting cells.", details: [] }]
    });
    expect(cleanMemoryLine("v1")).toBe("");
    expect(cleanMemoryLine("- **Bold** `code` (see rollout_summaries/x.md)")).toBe("Bold code");
    expect(buildNativeMemoryView(LEGACY_PLACEHOLDER)).toBeUndefined();
  });

  it("detects the summary language", () => {
    expect(detectMemoryLanguage("Prefers answers in Chinese with the conclusion first.")).toBe("en");
    expect(detectMemoryLanguage("用户偏好先给结论，常用 OMC 和 LTE eNodeB 排障。")).toBe("zh");
    expect(detectMemoryLanguage("Works with 张三 on the Jakarta rollout of LTE small cells and OMC upgrades.")).toBe("en");
  });
});

describe("PortalMemoryService", () => {
  let root: string;
  let service: PortalMemoryService;
  let userDir: string;

  beforeEach(async () => {
    root = await mkdtemp(path.join(os.tmpdir(), "portal-memory-"));
    service = new PortalMemoryService({ sessionHomeRoot: root });
    userDir = path.join(root, "internal", "user1");
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  async function codexHome(hash: string, options: { summary?: string; handbook?: string; legacyRaw?: string; inHomeSource?: boolean; mtime?: string } = {}) {
    const home = path.join(userDir, `agent-general-${hash}`);
    const memories = path.join(home, "memories");
    await mkdir(memories, { recursive: true });
    if (options.summary !== undefined) await writeFile(path.join(memories, "memory_summary.md"), options.summary, "utf8");
    if (options.handbook !== undefined) await writeFile(path.join(memories, "MEMORY.md"), options.handbook, "utf8");
    if (options.legacyRaw !== undefined) {
      const dir = options.inHomeSource ? path.join(home, ".agent-studio", "memory-source") : memories;
      await mkdir(dir, { recursive: true });
      await writeFile(path.join(dir, "raw_memories.md"), options.legacyRaw, "utf8");
    }
    if (options.mtime) {
      const time = new Date(options.mtime);
      for (const name of ["memory_summary.md", "MEMORY.md", "raw_memories.md"]) {
        await utimes(path.join(memories, name), time, time).catch(() => undefined);
      }
    }
    return home;
  }

  async function homeFor(scopeId = "internal~agent-general") {
    return service.resolveHome("user1", scopeId);
  }

  it("adds, edits and deletes user memories and projects them into every home of the assistant", async () => {
    const older = await codexHome("aaaaaa", { summary: NATIVE_SUMMARY, mtime: "2026-09-01T00:00:00Z" });
    const newer = await codexHome("bbbbbb", { summary: NATIVE_SUMMARY, mtime: "2026-10-01T00:00:00Z" });

    const first = await service.add(await homeFor(), { text: "回答请使用中文，先给结论" });
    await service.add(await homeFor(), { text: "负责印尼区域 OMC 运维" });
    await expect(service.add(await homeFor(), { text: "回答请使用中文，先给结论" })).rejects.toMatchObject({ code: "duplicate_item" });

    const [scope] = await service.list("user1");
    expect(scope.id).toBe("internal~agent-general");
    expect(scope.userItems.map((item) => item.text)).toEqual(["回答请使用中文，先给结论", "负责印尼区域 OMC 运维"]);
    expect(scope.learned?.preferences).toHaveLength(2);
    expect(scope.learned?.language).toBe("en");

    for (const home of [older, newer]) {
      const summary = await readFile(path.join(home, "memories", "memory_summary.md"), "utf8");
      expect(summary).toContain("- 负责印尼区域 OMC 运维");
      expect(summary).toContain("## User Profile");
    }
    // The learned view never shows the user section back.
    expect(scope.learned?.profile).toEqual(["The user is a product manager who works on LTE base stations."]);

    const edited = await service.update(await homeFor(), first.id, { text: "回答用中文" });
    await service.remove(await homeFor(), (await service.list("user1"))[0].userItems[1].id);
    expect((await service.list("user1"))[0].userItems.map((item) => item.text)).toEqual(["回答用中文"]);
    expect(edited.createdAt).toBe(first.createdAt);
    expect(await service.countForCodexHome(newer)).toBe(1 + 2);

    await service.remove(await homeFor(), edited.id);
    expect(await readFile(path.join(newer, "memories", "memory_summary.md"), "utf8")).toBe(`${NATIVE_SUMMARY.trim()}\n`);
  });

  it("lists assistants without memory yet so users can add the first one", async () => {
    await mkdir(path.join(userDir, "agent-general-cccccc"), { recursive: true });
    const [scope] = await service.list("user1");
    expect(scope).toMatchObject({ id: "internal~agent-general", userItems: [], learned: undefined });
    await service.add(await homeFor(), { text: "喜欢表格" });
    expect(await readFile(path.join(userDir, "agent-general-cccccc", "memories", "memory_summary.md"), "utf8")).toContain("- 喜欢表格");
  });

  it("hides assistants without memory and falls back to the most recently used one", async () => {
    const touch = async (segment: string, at: string) => {
      const dir = path.join(userDir, segment);
      await mkdir(dir, { recursive: true });
      await utimes(dir, new Date(at), new Date(at));
    };
    await touch("agent-doc-dddddd", "2026-09-01T00:00:00Z");
    await touch("agent-hr-eeeeee", "2026-10-01T00:00:00Z");
    expect((await service.list("user1")).map((scope) => scope.id)).toEqual(["internal~agent-hr"]);
    // Hidden assistants still accept writes.
    await service.add(await homeFor("internal~agent-doc"), { text: "文档用中文" });
    await codexHome("ffffff", { summary: NATIVE_SUMMARY });
    expect((await service.list("user1")).map((scope) => scope.id).sort()).toEqual(["internal~agent-doc", "internal~agent-general"]);
  });

  it("merges an assistant's legacy organization-id directory into its current organization", async () => {
    const aliased = new PortalMemoryService({ sessionHomeRoot: root, organizationAliases: { org_internal: "internal" } });
    const current = await codexHome("aaaaaa");
    const legacy = path.join(root, "org_internal", "user1", "agent-general-999999");
    await mkdir(path.join(legacy, "memories"), { recursive: true });
    await writeFile(path.join(legacy, "memories", "memory_summary.md"), NATIVE_SUMMARY, "utf8");
    await mkdir(path.join(root, "org_internal", "user1", "agent-old-111111"), { recursive: true });

    const homes = await aliased.listUserHomes("user1");
    expect(homes.map((home) => home.id).sort()).toEqual(["internal~agent-general", "internal~agent-old"]);
    const general = homes.find((home) => home.id === "internal~agent-general")!;
    expect(general.homes).toEqual([current, legacy]);
    expect(userMemoryStoreDir(general.codexHome)).toBe(path.join(userDir, ".agent-studio-memory", "agent-general"));

    const [scope] = await aliased.list("user1");
    expect(scope).toMatchObject({ id: "internal~agent-general", organizationKey: "internal" });
    expect(scope.learned?.profile).toHaveLength(1);
    await aliased.add(await aliased.resolveHome("user1", "internal~agent-general"), { text: "喜欢表格" });
    expect(await readFile(path.join(current, "memories", "memory_summary.md"), "utf8")).toContain("- 喜欢表格");
    // Runs no longer start under the legacy key, so its Codex memory is shown but never rewritten.
    expect(await readFile(path.join(legacy, "memories", "memory_summary.md"), "utf8")).toBe(NATIVE_SUMMARY);
  });

  it("migrates hand-written legacy memories and drops auto-extracted ones", async () => {
    const legacyRaw = [
      "# Raw Memories",
      "",
      "## 2026-08-01T00:00:00.000Z",
      "- source: portal",
      "- memory: 自动提取的一条记忆",
      "",
      "## 2026-08-02T00:00:00.000Z",
      "- source: portal_user",
      "- category: preference",
      "- memory: 我手工添加的记忆",
      ""
    ].join("\n");
    const home = await codexHome("dddddd", { summary: LEGACY_PLACEHOLDER, handbook: LEGACY_PLACEHOLDER, legacyRaw, inHomeSource: true });

    await syncAgentStudioMemoryProjection(home);

    expect((await readUserMemories(home)).map((item) => [item.text, item.createdAt])).toEqual([
      ["我手工添加的记忆", "2026-08-02T00:00:00.000Z"]
    ]);
    const summary = await readFile(path.join(home, "memories", "memory_summary.md"), "utf8");
    expect(summary).toContain("- 我手工添加的记忆");
    expect(summary).not.toContain("自动提取");
    expect(summary).not.toContain("Generated by Agent Studio MemoryEngine");
    // The legacy Agent Studio handbook is removed so Codex rebuilds its own.
    await expect(stat(path.join(home, "memories", "MEMORY.md"))).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readFile(path.join(userMemoryStoreDir(home), "user_memories.json"), "utf8")).toContain("我手工添加的记忆");
  });

  it("removes legacy placeholders and leaves native-only homes byte-for-byte untouched", async () => {
    const placeholder = await codexHome("eeeeee", { summary: LEGACY_PLACEHOLDER });
    await syncAgentStudioMemoryProjection(placeholder);
    await expect(stat(path.join(placeholder, "memories", "memory_summary.md"))).rejects.toMatchObject({ code: "ENOENT" });

    const native = await codexHome("ffffff", { summary: NATIVE_SUMMARY, handbook: "# Task Group: native handbook\n" });
    const before = await stat(path.join(native, "memories", "memory_summary.md"));
    await syncAgentStudioMemoryProjection(native);
    expect(await readFile(path.join(native, "memories", "memory_summary.md"), "utf8")).toBe(NATIVE_SUMMARY);
    expect((await stat(path.join(native, "memories", "memory_summary.md"))).mtimeMs).toBe(before.mtimeMs);
    expect(await readFile(path.join(native, "memories", "MEMORY.md"), "utf8")).toContain("native handbook");
  });

  it("restores Codex's committed summary and handbook that the retired engine overwrote", async () => {
    const home = await codexHome("abcabc", { summary: NATIVE_SUMMARY, handbook: "# Task Group: native handbook\n" });
    const memories = path.join(home, "memories");
    const git = (...args: string[]) => execFileSync("git", ["-C", memories, ...args], { stdio: "pipe" });
    git("init", "-q");
    git("add", "-A");
    git("-c", "user.email=codex@example.test", "-c", "user.name=codex", "commit", "-q", "-m", "consolidation");
    await writeFile(path.join(memories, "memory_summary.md"), LEGACY_PLACEHOLDER, "utf8");
    await writeFile(path.join(memories, "MEMORY.md"), LEGACY_PLACEHOLDER, "utf8");

    await syncAgentStudioMemoryProjection(home);

    expect(await readFile(path.join(memories, "memory_summary.md"), "utf8")).toBe(NATIVE_SUMMARY);
    expect(await readFile(path.join(memories, "MEMORY.md"), "utf8")).toContain("native handbook");
    expect((await service.list("user1"))[0].learned?.preferences).toHaveLength(2);
  });

  it("keeps shared integration homes on Codex's own memory", async () => {
    const shared = path.join(root, "integrations", "zendesk", "inst-1", "agent-support-abcdef");
    await mkdir(path.join(shared, "memories"), { recursive: true });
    await writeFile(path.join(shared, "memories", "memory_summary.md"), NATIVE_SUMMARY, "utf8");
    await syncAgentStudioMemoryProjection(shared);
    expect(await readFile(path.join(shared, "memories", "memory_summary.md"), "utf8")).toBe(NATIVE_SUMMARY);
  });
});

describe("MemoryTranslationService", () => {
  const view = buildNativeMemoryView(NATIVE_SUMMARY)!;
  const translatedJson = JSON.stringify({
    profile: ["用户是负责 LTE 基站的产品经理。"],
    preferences: [
      { text: "偏好中文回答，先给结论。", details: ["对比时使用表格。"] },
      { text: "希望钉钉总结简短", details: [] }
    ],
    tips: [{ text: "重启小区前先检查 OMC 告警。", details: [] }]
  });

  it("translates once, caches by content hash and records usage through the usage recorder", async () => {
    const storeDir = await mkdtemp(path.join(os.tmpdir(), "memory-translation-"));
    const callLlm = vi.fn(async () => ({ text: translatedJson, usage: { inputTokens: 800, cachedInputTokens: 512, outputTokens: 200 } }));
    const recordDirectUsage = vi.fn(async () => undefined);
    const service = new MemoryTranslationService({
      resolveLlmConfig: async () => ({ provider: "openai_compatible", apiMode: "chat_completions", baseUrl: "https://api.deepseek.com", apiKey: "k", model: "deepseek-v4-flash" }),
      recordDirectUsage,
      callLlm
    });
    const input = { storeDir, view, target: "zh" as const, actor: { userId: "user1", organizationId: "org1" }, scopeId: "internal~agent-general" };

    const first = await service.translate(input);
    const second = await service.translate(input);

    expect(first.preferences[0]).toEqual({ text: "偏好中文回答，先给结论。", details: ["对比时使用表格。"] });
    expect(second).toEqual(first);
    expect(await service.cached(storeDir, view, "zh")).toEqual(first);
    expect(callLlm).toHaveBeenCalledTimes(1);
    expect(recordDirectUsage).toHaveBeenCalledTimes(1);
    expect(recordDirectUsage).toHaveBeenCalledWith(expect.objectContaining({
      organizationId: "org1",
      userId: "user1",
      model: "deepseek-v4-flash",
      featureType: "memory_translation",
      inputTokens: 800,
      cachedInputTokens: 512,
      outputTokens: 200,
      resultStatus: "success"
    }));
    // Same language: no call at all.
    expect(await service.translate({ ...input, target: "en" })).toBe(view);
    expect(callLlm).toHaveBeenCalledTimes(1);
    await rm(storeDir, { recursive: true, force: true });
  });

  it("records a failed call and keeps the original when the model breaks the shape", async () => {
    const storeDir = await mkdtemp(path.join(os.tmpdir(), "memory-translation-"));
    const recordDirectUsage = vi.fn(async () => undefined);
    const service = new MemoryTranslationService({
      resolveLlmConfig: async () => ({ provider: "openai", apiMode: "auto", baseUrl: "https://api.openai.com/v1", apiKey: "k", model: "m" }),
      recordDirectUsage,
      callLlm: vi.fn(async () => { throw new Error("upstream 500"); })
    });
    await expect(service.translate({ storeDir, view, target: "zh", actor: { userId: "u" }, scopeId: "s" })).rejects.toMatchObject({ code: "translation_failed" });
    expect(recordDirectUsage).toHaveBeenCalledWith(expect.objectContaining({ resultStatus: "failed", inputTokens: 0, outputTokens: 0 }));

    const partial = parseTranslation(JSON.stringify({ profile: ["译文"], preferences: [{ text: "只有一条" }], tips: [] }), view);
    expect(partial.profile).toEqual(["译文"]);
    expect(partial.preferences).toEqual(view.preferences);
    expect(partial.tips).toEqual(view.tips);
    await rm(storeDir, { recursive: true, force: true });
  });

  it("reports unavailable when no memory LLM is configured", async () => {
    const service = new MemoryTranslationService({ resolveLlmConfig: async () => undefined, recordDirectUsage: vi.fn() });
    await expect(service.translate({ storeDir: os.tmpdir(), view, target: "zh", actor: { userId: "u" }, scopeId: "s" })).rejects.toMatchObject({ code: "translation_unavailable" });
  });
});
