import { execFile } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";

import {
  AGENT_STUDIO_MEMORY_SOURCE_RELATIVE_PATH,
  agentStudioMemoryStore,
  codexMemoryProjectionPath,
  listSiblingCodexHomes,
  normalizedMemoryKey,
  pathExists
} from "./engine.js";

/**
 * Agent Studio no longer generates memories itself: Codex native memory owns everything it
 * learns from conversations. The only memories Agent Studio keeps are the ones a user typed in
 * by hand. They live in one store per user (or integration) + assistant, beside the
 * per-capability Codex homes, and are projected into Codex's `memory_summary.md` as a marked
 * section so Codex's own content is never replaced.
 */

export const USER_MEMORIES_FILE_NAME = "user_memories.json";
export const USER_MEMORY_SECTION_START = "<!-- agent-studio:user-memories:start -->";
export const USER_MEMORY_SECTION_END = "<!-- agent-studio:user-memories:end -->";
/** Marker of summaries written by the retired Agent Studio MemoryEngine. */
export const LEGACY_AGENT_STUDIO_SUMMARY_MARKER = "Generated by Agent Studio MemoryEngine";
const IN_HOME_USER_MEMORY_RELATIVE_PATH = path.join(".agent-studio", "user-memory");
const execFileAsync = promisify(execFile);

export type UserMemoryItem = { id: string; text: string; createdAt: string; updatedAt: string };

export function userMemoryId(text: string): string {
  return createHash("sha256").update(text.trim()).digest("hex").slice(0, 16);
}

/** Directory holding the user-added memories of the assistant that owns `codexHome`. */
export function userMemoryStoreDir(codexHome: string): string {
  return agentStudioMemoryStore(codexHome)?.storeDir ?? path.join(codexHome, IN_HOME_USER_MEMORY_RELATIVE_PATH);
}

async function readTextIfExists(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return "";
    throw error;
  }
}

function isoOr(value: unknown, fallback: string): string {
  return typeof value === "string" && !Number.isNaN(Date.parse(value)) ? value : fallback;
}

function normalizeItems(value: unknown): UserMemoryItem[] {
  const list = Array.isArray((value as { items?: unknown })?.items) ? (value as { items: unknown[] }).items : [];
  const now = new Date().toISOString();
  const seen = new Set<string>();
  const items: UserMemoryItem[] = [];
  for (const entry of list) {
    const record = entry as Record<string, unknown>;
    const text = typeof record?.text === "string" ? record.text.replace(/\s+/g, " ").trim() : "";
    if (!text) continue;
    const key = normalizedMemoryKey(text);
    if (seen.has(key)) continue;
    seen.add(key);
    const createdAt = isoOr(record.createdAt, now);
    items.push({ id: userMemoryId(text), text, createdAt, updatedAt: isoOr(record.updatedAt, createdAt) });
  }
  return items;
}

/** `- source: portal_user` entries of a legacy raw_memories.md (the only hand-written ones). */
export function legacyUserMemoryEntries(content: string): Array<{ text: string; at?: string }> {
  const entries: Array<{ text: string; at?: string }> = [];
  for (const chunk of content.split(/\n(?=## )/)) {
    if (!chunk.startsWith("## ")) continue;
    if (chunk.match(/^- source:\s*(.+)$/m)?.[1]?.trim() !== "portal_user") continue;
    const text = chunk.match(/^- memory:\s*(.+)$/m)?.[1]?.trim();
    if (!text) continue;
    const at = chunk.slice(3, chunk.indexOf("\n") < 0 ? undefined : chunk.indexOf("\n")).trim();
    entries.push({ text, at: Number.isNaN(Date.parse(at)) ? undefined : at });
  }
  return entries;
}

/**
 * Hand-written memories saved before this store format existed. A previously built store
 * already merged every home of the assistant, so it wins; otherwise read each home's
 * legacy source and projection.
 */
async function legacyUserMemories(codexHome: string): Promise<UserMemoryItem[]> {
  const store = agentStudioMemoryStore(codexHome);
  const files: string[] = [];
  if (store && (await pathExists(path.join(store.storeDir, "raw_memories.md")))) {
    files.push(path.join(store.storeDir, "raw_memories.md"));
  } else {
    const homes = store ? await listSiblingCodexHomes(store.parentDir, store.segmentBase) : [codexHome];
    for (const home of homes) {
      files.push(path.join(home, AGENT_STUDIO_MEMORY_SOURCE_RELATIVE_PATH, "raw_memories.md"));
      files.push(path.join(codexMemoryProjectionPath(home), "raw_memories.md"));
    }
  }
  const raw: Array<{ text: string; createdAt?: string; updatedAt?: string }> = [];
  for (const file of files) {
    for (const entry of legacyUserMemoryEntries(await readTextIfExists(file))) {
      raw.push({ text: entry.text, createdAt: entry.at, updatedAt: entry.at });
    }
  }
  return normalizeItems({ items: raw });
}

async function writeJsonAtomic(filePath: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const tempPath = `${filePath}.tmp-${randomUUID().slice(0, 8)}`;
  await fs.writeFile(tempPath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
  await fs.rename(tempPath, filePath);
}

export async function readUserMemories(codexHome: string): Promise<UserMemoryItem[]> {
  const filePath = path.join(userMemoryStoreDir(codexHome), USER_MEMORIES_FILE_NAME);
  const content = await readTextIfExists(filePath);
  if (content) {
    try {
      return normalizeItems(JSON.parse(content));
    } catch {
      return [];
    }
  }
  const migrated = await legacyUserMemories(codexHome);
  // Persist migrated items once so later reads skip the legacy scan.
  if (migrated.length) await writeJsonAtomic(filePath, { version: 1, items: migrated });
  return migrated;
}

export async function writeUserMemories(codexHome: string, items: UserMemoryItem[]): Promise<void> {
  await writeJsonAtomic(path.join(userMemoryStoreDir(codexHome), USER_MEMORIES_FILE_NAME), { version: 1, items });
}

function userMemorySection(items: UserMemoryItem[]): string {
  return [
    USER_MEMORY_SECTION_START,
    "<!-- Managed by Agent Studio and regenerated before every run. Do not edit, move, or copy these lines into other memory files. -->",
    "## Memories the user added",
    "",
    "The user wrote these themselves. Treat them as explicit, current facts and instructions; they override conflicting older memories.",
    "",
    ...items.map((item) => `- ${item.text}`),
    USER_MEMORY_SECTION_END
  ].join("\n");
}

/** Codex's own part of a memory summary: legacy Agent Studio summaries and the managed section removed. */
export function nativeMemorySummary(content: string): string {
  if (content.includes(LEGACY_AGENT_STUDIO_SUMMARY_MARKER)) return "";
  const start = content.indexOf(USER_MEMORY_SECTION_START);
  if (start < 0) return content;
  const end = content.indexOf(USER_MEMORY_SECTION_END, start);
  const tail = end < 0 ? "" : content.slice(end + USER_MEMORY_SECTION_END.length);
  return `${content.slice(0, start).trimEnd()}\n\n${tail.trimStart()}`.trim();
}

/** The summary Codex should read: user-added memories first (they survive prompt truncation), then Codex's own. */
export function composeMemorySummary(current: string, items: UserMemoryItem[]): string {
  const native = nativeMemorySummary(current);
  const untouched = native === current;
  if (!items.length) {
    if (!native.trim()) return "";
    return untouched ? current : `${native.trim()}\n`;
  }
  return native.trim() ? `${userMemorySection(items)}\n\n${native.trim()}\n` : `${userMemorySection(items)}\n`;
}

/**
 * Codex commits its memory folder to a git repo after each consolidation. The retired Agent
 * Studio engine overwrote the working copy without committing, so the last committed file is
 * usually Codex's own version. Returns it when it exists and is not an Agent Studio file.
 */
async function committedNativeFile(projectionDir: string, fileName: string): Promise<string | undefined> {
  if (!(await pathExists(path.join(projectionDir, ".git")))) return undefined;
  try {
    const { stdout } = await execFileAsync("git", ["-C", projectionDir, "show", `HEAD:${fileName}`], {
      timeout: 5000,
      maxBuffer: 4 * 1024 * 1024
    });
    return stdout.trim() && !stdout.includes(LEGACY_AGENT_STUDIO_SUMMARY_MARKER) ? stdout : undefined;
  } catch {
    return undefined;
  }
}

/** Replaces a retired Agent Studio file with Codex's committed version, or removes it so Codex rebuilds it. */
async function repairLegacyFile(projectionDir: string, fileName: string): Promise<string> {
  const filePath = path.join(projectionDir, fileName);
  const current = await readTextIfExists(filePath);
  if (!current.includes(LEGACY_AGENT_STUDIO_SUMMARY_MARKER)) return current;
  const committed = await committedNativeFile(projectionDir, fileName);
  if (committed) {
    await fs.writeFile(filePath, committed, "utf8");
    return committed;
  }
  await fs.rm(filePath, { force: true });
  return "";
}

/**
 * Brings `<codexHome>/memories` in line with the user's hand-written memories without touching
 * what Codex generated. Also repairs leftovers of the retired Agent Studio MemoryEngine, which
 * used to overwrite Codex's summary and handbook. Writes only when something changes.
 */
export async function syncAgentStudioMemoryProjection(codexHome: string): Promise<void> {
  const items = await readUserMemories(codexHome);
  const projectionDir = codexMemoryProjectionPath(codexHome);
  await repairLegacyFile(projectionDir, "MEMORY.md");
  const summaryPath = path.join(projectionDir, "memory_summary.md");
  const current = await repairLegacyFile(projectionDir, "memory_summary.md");
  const next = composeMemorySummary(current, items);
  if (next !== current) {
    if (next) {
      await fs.mkdir(projectionDir, { recursive: true });
      await fs.writeFile(summaryPath, next, "utf8");
    } else {
      await fs.rm(summaryPath, { force: true });
    }
  }
}
