#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
base="$(cd "$script_dir/.." && pwd -P)"
script="$base/scripts/install-ubuntu.sh"

test -f "$script"
grep -q -- '--domain' "$script"
grep -q -- '--repo-url' "$script"
grep -q -- '--repo-dir' "$script"
grep -q -- '--deploy-key-path' "$script"
grep -q -- '--skip-codex-check' "$script"
grep -q -- '--force-phase' "$script"
grep -q -- '--force-all' "$script"
grep -q 'load_existing_state' "$script"
grep -q 'ensure_app_user' "$script"
grep -q 'ensure_base_directories' "$script"
grep -q 'ensure_deploy_key' "$script"
grep -q 'attempt_clone' "$script"
grep -q 'ensure_postgres_setup' "$script"
grep -q 'ensure_env_files' "$script"
grep -q 'ensure_caddy_config' "$script"
grep -q 'run_first_deploy' "$script"
grep -q 'ensure_pm2_start' "$script"
grep -q 'ensure_codex_verification' "$script"
grep -q 'phase_forced' "$script"
grep -q 'maybe_mark_phase_forced' "$script"
grep -q 'record_step_status app_user' "$script"
grep -q 'record_step_status base_directories' "$script"
grep -q 'record_step_status repo_clone' "$script"
grep -q 'record_step_status postgres' "$script"
grep -q 'postgres_user_status' "$script"
grep -q 'postgres_db_status' "$script"
grep -q 'record_step_status caddy_config' "$script"
grep -q 'record_step_status first_deploy' "$script"
grep -q 'record_step_status first_deploy attempted' "$script"
grep -q 'actual deploy execution started' "$script"
grep -q 'npm run build' "$script"
grep -q 'record_step_status pm2_start' "$script"
grep -q 'record_step_status codex_runtime_check' "$script"
grep -q 'backend_env_status' "$script"
grep -q 'frontend_env_status' "$script"
grep -q 'record_step_status repo_clone skipped' "$script"
grep -q 'record_step_status codex_runtime_check skipped' "$script"
grep -q 'codex_runtime_check_skipped' "$script"
grep -q 'state_has repo_dir' "$script"
grep -q 'state_has deploy_key_path' "$script"
grep -q 'git clone' "$script"
