const root = document.querySelector('#app');
let state = { connected: false, paired: false, roots: [], deviceName: '', error: '', paused: false };
let busy = false, enteredCode = '';
const esc = value => String(value || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => ICONS[name] || '';
function render() {
  root.innerHTML = `<div class="shell"><aside><div class="brand">${icon('sparkles')}<strong>Agent Studio</strong></div><div class="nav">${icon('monitor')} 我的电脑</div><small class="version">桌面客户端 ${esc(state.version || '0.2.1')}</small></aside><section class="content"><header><div class="device-icon">${icon('monitor')}</div><h1>${state.connected ? '这台电脑已连接' : state.paused ? '连接已暂停' : state.paired ? '正在连接你的电脑' : '连接你的电脑'}</h1><p>${state.paired ? '在 Portal 选择工作目录，即可让 Agent 在这台电脑上处理任务。' : '在 Portal 点击「使用电脑文件夹」，然后打开桌面客户端。'}</p></header>${state.error ? `<div role="alert" class="error">${esc(state.error)}</div>` : ''}<div class="device"><div><strong>${esc(state.deviceName || '我的电脑')}</strong><span><i class="dot ${state.connected ? 'online' : ''}"></i>${state.connected ? '已连接' : state.paused ? '已暂停' : state.paired ? '正在重试连接…' : '等待连接'}</span></div>${icon('monitor')}</div>${state.paired ? `<div class="section-title"><h2>最近使用的文件夹</h2><span>${state.roots.length} 个</span></div><div class="folders">${state.roots.length ? state.roots.map(r => `<div class="folder">${icon('folder')}<div><strong>${esc(r.label || r.path)}</strong><small title="${esc(r.path)}">${esc(r.path)}</small></div>${icon('check')}</div>`).join('') : '<p class="empty">选择一个文件夹开始工作</p>'}</div><div class="actions"><button class="primary" id="choose" ${busy || state.paused ? 'disabled' : ''}>${icon('folderPlus')}${busy ? '正在处理…' : '选择文件夹'}</button><button id="portal">打开 Portal ${icon('arrowUpRight')}</button></div><p class="trust">命令以你的电脑账号运行，所选文件夹是默认工作目录。</p><footer><button class="text" id="pause">${state.paused ? '恢复连接' : '暂停连接'}</button><button class="text muted" id="disconnect">退出连接</button></footer>` : `<div class="connect-card"><button class="primary" id="portal">打开 Portal ${icon('arrowUpRight')}</button><details><summary>使用配对码连接</summary><label for="code">Portal 中的一次性配对码</label><div class="code-row"><input id="code" autocomplete="one-time-code" maxlength="10" value="${esc(enteredCode)}" placeholder="输入配对码"><button class="primary" id="pair" ${busy ? 'disabled' : ''}>${busy ? '连接中…' : '连接'}</button></div></details></div>`}</section></div>`;
  const action = (id, fn) => document.getElementById(id)?.addEventListener('click', async () => { if (busy) return; busy = true; state.error = ''; render(); try { await fn(); } catch (e) { state.error = e.message; } finally { busy = false; render(); } });
  document.getElementById('code')?.addEventListener('input', e => { enteredCode = e.target.value; });
  action('pair', () => window.bridgeApp.pair(enteredCode.trim())); action('choose', () => window.bridgeApp.chooseRoot()); action('portal', () => window.bridgeApp.openPortal()); action('pause', () => window.bridgeApp.pause()); action('disconnect', () => window.bridgeApp.disconnect());
}
window.bridgeApp.getState().then(value => { state = value; render(); });
window.bridgeApp.onState(value => { state = value; render(); });
