const root = document.querySelector("#app");
const state = { connected: false, roots: [], error: "", pairing: false };
const esc = (value) => String(value || "").replace(/[&<>\"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
function render() { root.innerHTML = `<div class="shell"><aside><div class="brand"><span class="brand-mark">✦</span><div><strong>Agent Studio</strong><small>Local Bridge</small></div></div><div class="side-label">本机连接</div><div class="side-item active"><span>◉</span>连接状态</div><div class="side-item"><span>⌂</span>授权目录</div><div class="side-spacer"></div><div class="privacy"><span>◈</span><div><b>安全连接</b><small>只允许访问你选择的目录</small></div></div></aside><section class="content"><header><div><p class="eyebrow">LOCAL COMPANION</p><h1>连接你的电脑</h1><p class="sub">让云端 Agent 在你授权的范围内读取和修改本地文件。</p></div><div class="status ${state.connected ? "online" : "offline"}"><i></i>${state.connected ? "已连接" : "未连接"}</div></header>${state.error ? `<div class="error">${esc(state.error)}</div>` : ""}${state.connected ? connectedView() : pairingView()}</section></div>`; bind(); }
function pairingView() { return `<div class="hero-card"><div class="orb">⌘</div><div><span class="kicker">STEP 01 · PAIR DEVICE</span><h2>输入 Portal 中的配对码</h2><p>打开 Agent Studio Portal → 我的电脑 → 连接新电脑，输入显示的 8 位配对码。</p></div><label>配对码<input id="code" inputmode="text" autocomplete="one-time-code" maxlength="8" placeholder="例如 7F3A91C2"/></label><button class="primary" id="pair">${state.pairing ? "正在连接…" : "连接到 Agent Studio"}<span>→</span></button><div class="hint"><span>✓</span>配对码仅 10 分钟有效，使用后立即失效</div></div><div class="steps"><div class="step current"><b>01</b><span>输入配对码</span></div><div class="line"></div><div class="step"><b>02</b><span>授权目录</span></div><div class="line"></div><div class="step"><b>03</b><span>开始工作</span></div></div>`; }
function connectedView() { return `<div class="connected-card"><div class="connected-head"><div class="pulse">✓</div><div><span class="kicker">DEVICE CONNECTED</span><h2>这台电脑已准备就绪</h2><p>云端 Agent 可以访问下方授权的目录。</p></div></div><div class="metric"><span>设备名称</span><strong>${esc(state.name || "本机")}</strong><small>在线 · 安全轮询已开启</small></div><div class="folders"><div class="section-title"><span>授权目录</span><button id="add-root" class="secondary">＋ 添加目录</button></div>${state.roots.length ? state.roots.map((r) => `<div class="folder"><span class="folder-icon">⌁</span><div><b>${esc(r.split(/[\\/]/).pop() || r)}</b><small>${esc(r)}</small></div><span class="check">✓</span></div>`).join("") : `<div class="empty">还没有授权目录，添加一个目录后云端才能访问本机文件。</div>`}</div><button id="disconnect" class="danger">断开这台电脑</button></div>`; }
function bind() { document.querySelector("#pair")?.addEventListener("click", async () => { const code = document.querySelector("#code").value.trim(); if (code.length < 4) { state.error = "请输入 Portal 中显示的配对码"; render(); return; } state.pairing = true; state.error = ""; render(); try { const result = await window.bridgeApp.pair(code); state.connected = true; state.name = result.name; } catch (error) { state.error = error.message || "配对失败，请检查配对码和网络连接"; } finally { state.pairing = false; render(); } }); document.querySelector("#add-root")?.addEventListener("click", async () => { try { const root = await window.bridgeApp.chooseRoot(); if (root) state.roots = [...new Set([...state.roots, root])]; render(); } catch (error) { state.error = error.message; render(); } }); document.querySelector("#disconnect")?.addEventListener("click", async () => { await window.bridgeApp.disconnect(); state.connected = false; state.roots = []; render(); }); }
window.bridgeApp.getState().then((saved) => { Object.assign(state, saved, { connected: Boolean(saved.token), roots: saved.roots || [] }); render(); });
window.bridgeApp.on("bridge:status", (payload) => { state.connected = payload.connected; if (payload.roots) state.roots = payload.roots; if (payload.error) state.error = payload.error; render(); });
window.bridgeApp.on("bridge:roots", (roots) => { state.roots = roots; render(); });
