import type { SkillCatalogLocalizedContent } from "./types.js";

export type CuratedSkillPresentation = {
  zh: SkillCatalogLocalizedContent;
  en: SkillCatalogLocalizedContent;
};

function content(
  displayName: string,
  summary: string,
  useCases: string[],
  usageSteps: string[],
  examplePrompts: string[],
  dataScope: string
): SkillCatalogLocalizedContent {
  return { displayName, summary, useCases, usageSteps, examplePrompts, dataScope };
}

export const CURATED_SKILL_PRESENTATIONS: Record<string, CuratedSkillPresentation> = {
  "1-core-network-month-alarm-report": {
    zh: content("核心网告警月报", "从标准 Zabbix 报表环境生成指定月份的核心网告警报告", ["生成核心网月度告警报告", "核对中英文报告文件", "获取可预览的 HTML 报告"], ["提供需要统计的年份和月份", "连接固定报表环境并运行标准脚本", "核验结果后返回中文和英文预览"], ["生成 2026 年 7 月的核心网告警月报。", "重新生成上个月的中英文核心网告警报告。"], "固定生产 Zabbix 报表环境中当前账号获准访问的告警与报表数据"),
    en: content("Core Network Alarm Report", "Generate monthly core-network alarm reports from the standard Zabbix reporting environment", ["Create a monthly core-network alarm report", "Verify Chinese and English report files", "Retrieve previewable HTML reports"], ["Provide the target year and month", "Run the standard scripts in the fixed reporting environment", "Verify and return both report previews"], ["Create the core-network alarm report for July 2026.", "Regenerate last month's Chinese and English alarm reports."], "Alarm and report data accessible to the authorized account in the fixed production Zabbix environment")
  },
  "analyze-kpi-evidence": {
    zh: content("KPI 证据分析", "按明确口径审查 KPI 异常、基线和关联证据，不越过证据下根因结论", ["排查站点或小区 KPI 劣化", "比较变更前后指标", "关联告警、版本和邻区变化"], ["提供数据文件、时区和分析范围", "确认阈值、低流量排除和基线规则", "输出可审计发现并标明待确认根因"], ["分析这份 KPI 表里最近一周的性能劣化。", "比较升级前后 KPI，并关联同期告警。"], "用户提供或明确授权访问的表格、数据库导出和粘贴数据；不会自行操作网络设备"),
    en: content("KPI Evidence Analysis", "Review KPI anomalies, baselines, and correlated evidence without overstating root cause", ["Investigate site or cell KPI degradation", "Compare metrics before and after a change", "Correlate alarms, versions, and neighbor changes"], ["Provide the data, time zone, and analysis scope", "Confirm thresholds, low-traffic exclusions, and baseline rules", "Return auditable findings with unconfirmed causes clearly marked"], ["Analyze performance degradation in this KPI file for the past week.", "Compare KPIs before and after the upgrade and correlate alarms."], "User-provided or explicitly authorized tables and exports; never operates network devices")
  },
  "analyze-packet-capture-evidence": {
    zh: content("抓包证据分析", "只读分析抓包与日志，先校验采集完整性再判断协议和信令问题", ["分析 PCAP/PCAPNG 信令流程", "定位重传、时延和协议失败", "与正常样本或日志做对比"], ["提供抓包、日志和采集点说明", "核对时间基准、接口覆盖和同一用户标识", "在证据边界内输出流程和异常结论"], ["分析这个 PCAP 中的接入失败流程。", "对比异常与正常抓包，找出重传和时延差异。"], "仅使用用户提供的抓包、日志和对照样本；不会连接、查询或配置网络设备"),
    en: content("Packet Capture Evidence Analysis", "Analyze captures and logs read-only after validating collection integrity and coverage", ["Analyze PCAP or PCAPNG signaling", "Locate retransmissions, delays, and protocol failures", "Compare an issue capture with logs or a normal baseline"], ["Provide captures, logs, and capture-point context", "Validate time basis, interface coverage, and same-user identity", "Report sequence evidence and bounded conclusions"], ["Analyze the access failure sequence in this PCAP.", "Compare the failing and normal captures for retransmission and delay differences."], "Only user-provided captures, logs, and comparison samples; never connects to or changes network devices")
  },
  "analyze-telecom-competitors": {
    zh: content("通信竞品分析", "基于可引用证据研究通信厂商、产品和市场策略，并输出管理层可用报告", ["对比竞品型号与技术能力", "研究供应链、认证和市场策略", "制作竞品分析文档或演示文稿"], ["说明竞品、产品和决策问题", "确定快速、标准或深度研究范围", "核对来源并生成 Markdown、Word 或 PPT"], ["对比这两款室外 CPE 的硬件、软件和市场定位。", "生成某竞品核心网产品的管理层分析 PPT。"], "公开可信来源、用户提供的资料及当前账号获准访问的数据；关键结论保留出处"),
    en: content("Telecom Competitive Analysis", "Research telecom vendors, products, and strategies with citable evidence and decision-ready outputs", ["Benchmark competitor products and technology", "Research supply chain, certification, and market strategy", "Create competitive-analysis documents or presentations"], ["Specify the competitor, product, and decision question", "Choose a quick, standard, or deep research scope", "Verify sources and deliver Markdown, Word, or PowerPoint"], ["Compare these outdoor CPE models on hardware, software, and positioning.", "Create an executive presentation on a competitor's core-network portfolio."], "Credible public sources, user-provided material, and authorized data, with sources retained for material claims")
  },
  "baicells-config-guide-synthesis": {
    zh: content("配置指南合成", "按模板和目标版本资料合成可交付的佰才邦基站配置指南", ["从多份版本文档合成配置指南", "迁移目标版本内容与图表", "校验并美化交付级 Word 文档"], ["提供结构模板和目标版本源文档", "完成资料完整性与目标版本证据检查", "生成、渲染并逐页核验 DOCX"], ["按这个模板合成 Nova 系列目标版本配置指南。", "继续完善这份配置指南并检查图片和表格。"], "仅使用用户提供的模板、目标版本资料和任务生成文件"),
    en: content("Configuration Guide Synthesis", "Build a delivery-ready Baicells base-station configuration guide from a template and target-version sources", ["Synthesize a guide from multiple version documents", "Migrate target-version text, images, and tables", "Validate and polish a delivery-grade Word document"], ["Provide the structure template and target-version sources", "Audit source completeness and target-version evidence", "Generate, render, and inspect the DOCX page by page"], ["Build the target-version Nova configuration guide from this template.", "Continue this guide and verify every image and table."], "Only user-provided templates, target-version sources, and files generated for the task")
  },
  "batch-template-docs": {
    zh: content("批量模板文档", "用已批准的训练数据批量生成模板化人员文档，并先做严格校验和预览", ["批量生成 DOCX 或文本模板", "校验人员数据与占位符", "执行受控的邮件合并训练"], ["提供模板和已批准的数据清单", "校验必填值、唯一人员和日期范围", "先生成两份预览，确认后再批量生成"], ["用这份批准的培训数据生成两份预览。", "确认预览后批量生成全部人员文档。"], "仅使用明确批准且绑定到文件清单的培训数据；不使用生产或未批准的人员数据"),
    en: content("Batch Template Documents", "Generate template-based personnel documents from approved training data with validation and preview gates", ["Batch-generate DOCX or text templates", "Validate personnel data and placeholders", "Run controlled mail-merge training"], ["Provide the template and approved data manifest", "Validate required values, unique people, and date ranges", "Generate exactly two previews before approved batch output"], ["Generate two previews from this approved training dataset.", "The previews are approved; generate the remaining personnel documents."], "Only explicitly approved training data bound to the supplied manifest; never production or unapproved personnel data")
  },
  "bss-report": {
    zh: content("BSS 月度报告", "从两个月的 EML 附件生成 Zed BSS 月度 HTML 报告", ["生成 BSS 月报", "汇总两个月邮件附件数据", "获取可预览的 HTML 报告"], ["提供目标月份及所需 EML 文件", "在固定报表环境运行标准流程", "核验并下载月报预览"], ["用这两个月的 EML 生成 2026 年 7 月 BSS 月报。", "重新生成上月 BSS 报告并返回预览。"], "用户提供的 EML 与固定 Zed BSS 报表服务器中当前账号获准访问的数据"),
    en: content("BSS Monthly Report", "Generate a Zed BSS monthly HTML report from two months of EML attachments", ["Create a BSS monthly report", "Aggregate two months of email attachment data", "Retrieve a previewable HTML report"], ["Provide the target month and required EML files", "Run the standard workflow in the fixed reporting environment", "Verify and download the monthly preview"], ["Create the July 2026 BSS report from these two months of EML files.", "Regenerate last month's BSS report and return the preview."], "User-provided EML files and data accessible to the authorized account on the fixed Zed BSS reporting server")
  },
  "build-baicells-network-health-report": {
    zh: content("网络健康评估报告", "综合 OMC 告警、4G KPI、站点和规划数据生成网络健康 PPT 与审计明细", ["生成 4G 网络健康报告", "汇总告警、KPI 和负荷问题", "输出管理 PPT 与 Excel 明细"], ["提供所需 CSV 和 XLSX 数据", "核对时间范围、字段和站点口径", "生成并校验 PPTX 与审计工作簿"], ["用这些 OMC 和 KPI 文件生成网络健康报告。", "更新日报并补充问题闭环 Excel 明细。"], "用户提供的 OMC、KPI、站点监控和规划文件及本任务生成的报告"),
    en: content("Network Health Assessment", "Combine OMC alarms, 4G KPIs, site, and planning data into an executive deck and auditable workbook", ["Create a 4G network-health report", "Summarize alarm, KPI, and load issues", "Deliver a management deck and Excel evidence"], ["Provide the required CSV and XLSX inputs", "Confirm period, fields, and site scope", "Generate and validate the PPTX and audit workbook"], ["Create a network-health assessment from these OMC and KPI files.", "Update the daily report and add an Excel issue-closure detail."], "User-provided OMC, KPI, station, monitoring, and planning files plus generated report artifacts")
  },
  "meeting-minutes-actions": {
    zh: content("会议纪要与行动项", "把原始会议记录整理为已确认决定、行动项、责任人、截止时间和待确认事项", ["整理会议纪要", "提取行动项和责任人", "更新决定、截止时间与待确认事项"], ["提供原始记录或现有纪要", "区分已确认决定和未定事项", "补齐责任人或标记待确认后输出"], ["整理这份会议记录并列出行动项。", "更新纪要中的责任人，缺少截止日的保留待确认。"], "仅使用用户提供的会议记录和明确确认的信息"),
    en: content("Meeting Minutes & Actions", "Turn meeting notes into confirmed decisions, actions, owners, due dates, and open questions", ["Structure meeting minutes", "Extract actions and owners", "Update decisions, deadlines, and open items"], ["Provide the raw notes or existing minutes", "Separate confirmed decisions from unresolved topics", "Clarify missing owners or mark unresolved fields before delivery"], ["Organize these notes and list every action item.", "Update the owners and leave missing deadlines as to be confirmed."], "Only user-provided meeting material and explicitly confirmed information")
  },
  "omc-operations": {
    zh: content("OMC 运维操作", "通过实时能力目录查询、诊断并按授权操作 OMC 管理的网络资源", ["查询站点、告警和性能", "诊断 OMC 管理资源", "执行经授权的配置或运维动作"], ["说明目标资源和要完成的操作", "实时查询可用能力及所需参数", "先展示关键影响，再按权限执行并返回结果"], ["查询这个站点当前告警和在线状态。", "检查可用操作后，按授权修改该设备参数。"], "当前账号获准访问的 OMC 资源与实时能力目录；变更操作受权限和确认约束"),
    en: content("OMC Operations", "Query, diagnose, and operate OMC-managed network resources through the live capability catalog", ["Check sites, alarms, and performance", "Diagnose OMC-managed resources", "Run authorized configuration or operations actions"], ["Describe the target resource and intended outcome", "Discover current capabilities and required parameters", "Show material impact before authorized execution and report the result"], ["Check this site's current alarms and online status.", "Discover the supported action, then change this device parameter with authorization."], "OMC resources and live capabilities available to the current account; state-changing actions remain permission- and confirmation-bound")
  },
  "oxm-operations": {
    zh: content("OXM 设备运维", "按设备软件版本匹配能力手册，安全查询和操作 OXM 管理的网络设备", ["查询设备状态、告警和拓扑", "分析无线、传输、日志和任务", "执行经授权的配置、文件或软件操作"], ["提供目标设备和业务目的", "识别软件版本并选择匹配能力", "通过连接器执行，核验结果与影响"], ["查询这台基站的状态、版本和当前告警。", "按当前版本能力检查并执行这个配置变更。"], "当前账号获准访问的 OXM 设备、版本化能力手册和操作结果；变更动作受权限及确认约束"),
    en: content("OXM Device Operations", "Use version-matched capability handbooks to safely query and operate OXM-managed devices", ["Check device status, alarms, and topology", "Analyze radio, transport, logs, and tasks", "Run authorized configuration, file, or software operations"], ["Provide the target device and operational goal", "Identify software version and select matching capabilities", "Execute through the connector and verify result and impact"], ["Check this base station's status, version, and active alarms.", "Use its current-version capability to validate and run this configuration change."], "OXM devices, versioned capability handbooks, and results available to the current account; changes remain permission- and confirmation-bound")
  },
  "power-outage-report": {
    zh: content("停电月报", "在固定报表环境按指定年月生成停电事件 HTML 月报", ["生成停电月报", "汇总停电次数、时长和影响", "获取可预览 HTML 报告"], ["提供需要统计的年份和月份", "在固定 SSH 环境运行标准报表流程", "核验结果并返回本地预览"], ["生成 2026 年 7 月停电月报。", "重新生成上个月的停电报告并返回预览。"], "固定生产报表环境中当前账号获准访问的停电数据"),
    en: content("Power Outage Monthly Report", "Generate a monthly outage HTML report for a specified year and month in the fixed reporting environment", ["Create a monthly outage report", "Summarize outage count, duration, and impact", "Retrieve a previewable HTML report"], ["Provide the target year and month", "Run the standard report process in the fixed SSH environment", "Verify the result and return a local preview"], ["Create the July 2026 power outage report.", "Regenerate last month's outage report and return the preview."], "Outage data accessible to the authorized account in the fixed production reporting environment")
  },
  "ppt-gen": {
    zh: content("分层可编辑演示文稿", "先生成视觉母版，再拆分资产并组装为文字可编辑、结构分层的 PPTX", ["制作高质量演示文稿", "把效果图复刻为可编辑 PPT", "生成分层背景、卡片、图标和文字"], ["说明主题、受众、页数和视觉要求", "生成母版并记录模块坐标", "拆分资产、组装 PPTX 并渲染检查"], ["为这个产品方案制作 10 页可编辑演示文稿。", "把这张效果图复刻为分层可编辑 PPT。"], "用户提供的内容和参考图，以及本任务生成的图像资产、坐标清单和 PPTX"),
    en: content("Layered Editable Presentation", "Create a visual master, split its assets, and assemble a layered PPTX with editable text", ["Create a polished presentation", "Rebuild a visual mockup as editable slides", "Generate layered backgrounds, cards, icons, and text"], ["Specify topic, audience, slide count, and visual direction", "Generate the visual master and coordinate manifest", "Assemble the layered PPTX and verify rendered slides"], ["Create a 10-slide editable deck for this product proposal.", "Rebuild this mockup as a layered, editable PowerPoint."], "User-provided content and references plus generated image assets, coordinate manifests, and presentation files")
  },
  "siteapp-surge-support": {
    zh: content("SiteApp 生产支持", "通过受控 SSH 读取 Surge 生产环境，以当前证据回答 SiteApp 使用和排障问题", ["查询 SiteApp 当前配置和数据", "解释页面流程与系统行为", "基于生产证据排查问题"], ["说明页面、对象和期望结果", "以只读方式核对生产代码、配置、数据或日志", "区分已确认事实与建议并给出操作路径"], ["为什么这个规划页面不能删除 Cell？", "检查生产环境中这个站点的当前规划状态。"], "受控 SSH 可读取的 SiteApp Surge 生产代码、配置、数据库和日志；默认只读，不执行未授权变更"),
    en: content("SiteApp Production Support", "Inspect the Surge production environment through controlled SSH to answer SiteApp usage and troubleshooting questions", ["Check current SiteApp configuration and data", "Explain workflows and system behavior", "Troubleshoot from live production evidence"], ["Describe the page, object, and expected outcome", "Inspect production code, configuration, data, or logs read-only", "Separate confirmed facts from recommendations and provide the supported path"], ["Why can't this planning page delete the Cell?", "Check this site's current planning state in production."], "SiteApp Surge production code, configuration, database, and logs accessible through controlled SSH; read-only by default with no unauthorized changes")
  },
  "ssh-device-inspector": {
    zh: content("SSH 设备检查", "通过授权 SSH 对 Linux 或 OpenWrt 设备做只读识别和升级前能力盘点", ["识别 CPE 或嵌入式设备", "盘点系统、硬件和可用命令", "生成安全的升级前设备画像"], ["提供 IP、端口和授权凭据", "执行只读系统与命令发现", "报告已确认信息和仍存在的不确定项"], ["通过 SSH 识别这台 CPE 的系统和硬件平台。", "为这台 OpenWrt 设备生成升级前只读检查报告。"], "用户明确授权的 SSH 设备及其只读系统信息；不会配置、重启或升级设备"),
    en: content("SSH Device Inspector", "Perform authorized read-only discovery of Linux or OpenWrt devices and build a pre-upgrade profile", ["Identify a CPE or embedded device", "Inventory OS, hardware, and available commands", "Create a safe pre-upgrade device profile"], ["Provide host, port, and authorized credentials", "Run read-only system and command discovery", "Report confirmed facts and remaining uncertainty"], ["Identify this CPE's operating system and hardware platform over SSH.", "Create a read-only pre-upgrade profile for this OpenWrt device."], "Explicitly authorized SSH devices and read-only system information; never configures, restarts, or upgrades a device")
  },
  "surge-vpn-manage": {
    zh: content("Surge VPN 管理", "为获授权管理员查询、添加或撤销 Surge WireGuard 用户和设备接入", ["查询当前 VPN 用户和设备", "新增用户并生成客户端配置", "撤销用户或设备访问"], ["说明要查询或变更的用户与设备", "核对管理员授权和当前 WireGuard 状态", "执行变更、验证结果并交付必要配置"], ["查询当前 Surge VPN 用户。", "新增两个 VPN 用户并生成各自配置。"], "Surge 生产 VPN 的授权用户、Peer 和 WireGuard 配置；仅为明确授权的管理请求执行变更"),
    en: content("Surge VPN Management", "Let authorized administrators query, add, or revoke Surge WireGuard users and device peers", ["List current VPN users and devices", "Add users and generate client configurations", "Revoke user or device access"], ["Specify the users or devices to query or change", "Verify administrator authorization and current WireGuard state", "Apply the change, verify it, and deliver required configuration"], ["List the current Surge VPN users.", "Add two VPN users and generate a configuration for each."], "Authorized Surge production VPN users, peers, and WireGuard configuration; changes only for explicitly authorized administration requests")
  },
  "test-daily-report": {
    zh: content("测试日报邮件", "把零散测试事实整理成规范的中文日报主题和可直接发送的富文本正文", ["生成版本测试日报", "整理测试进展与风险", "输出邮件主题和正文"], ["提供当日测试事实、版本和项目", "补齐或标记缺失的进展与风险信息", "生成可复制到邮箱的日报内容"], ["根据这些测试记录生成今天的日报邮件。", "按现有模板整理版本测试进展和风险。"], "仅使用用户提供的测试事实、表格和日志摘要；不会读取或发送真实邮件"),
    en: content("Test Daily Report Email", "Turn fragmented test facts into a structured Chinese daily-report subject and ready-to-send rich-text body", ["Create a software test daily report", "Organize progress and risks", "Produce an email subject and body"], ["Provide today's test facts, version, and project", "Complete or clearly mark missing progress and risk fields", "Generate content ready to copy into email"], ["Create today's test daily-report email from these notes.", "Organize this version's test progress and risks using the existing template."], "Only user-provided test facts, tables, and log summaries; does not read or send live email")
  },
  "text-metrics": {
    zh: content("文本指标统计", "统计纯文本和 Markdown 的行数、词数、字符数、空行和高频词", ["统计 TXT 或 Markdown 指标", "提取高频词", "比较文本规模和结构"], ["提供需要分析的文本文件", "说明需要的指标或 Top N", "返回统计结果和必要说明"], ["统计这份 Markdown 的行数、词数和字符数。", "列出这个 TXT 中出现最多的 20 个词。"], "仅使用用户提供的纯文本和 Markdown 文件"),
    en: content("Text Metrics", "Measure lines, words, characters, blank lines, and frequent terms in plain text and Markdown", ["Measure TXT or Markdown files", "Extract frequent terms", "Compare text size and structure"], ["Provide the text files", "Choose metrics or a Top N value", "Return the measurements with relevant notes"], ["Count lines, words, and characters in this Markdown file.", "List the 20 most frequent words in this TXT file."], "Only user-provided plain-text and Markdown files")
  },
  "weekly-alarm-operations-summary": {
    zh: content("每周告警运营摘要", "从一个或多个告警 CSV 生成简洁、可审计的每周运营摘要", ["汇总每周告警量和趋势", "分析级别、状态和高频类型", "整理未解决重点和后续动作"], ["提供告警 CSV 和报告周期", "检查数据质量、字段和时间范围", "输出趋势、重点对象和保守行动建议"], ["汇总这些 CSV 的本周告警运营情况。", "比较本周每天的告警趋势并列出未解决重点。"], "仅使用用户提供的告警 CSV；建议不会被表述为已确认根因或已执行动作"),
    en: content("Weekly Alarm Operations Summary", "Create a concise, auditable weekly operations summary from one or more alarm CSV files", ["Summarize weekly alarm volume and trend", "Analyze severity, status, and top alarm types", "List unresolved priorities and follow-up actions"], ["Provide alarm CSV files and the reporting period", "Validate data quality, fields, and time range", "Report trends, affected objects, and conservative next actions"], ["Summarize this week's alarm operations from these CSV files.", "Compare daily alarm trends and list unresolved priorities."], "Only user-provided alarm CSV files; recommendations are not presented as confirmed root causes or completed actions")
  },
  "write-weekly-report": {
    zh: content("周报整理", "根据当期事实生成或修改固定为“结果、风险、下周动作”的简洁 Markdown 周报", ["编写个人或项目周报", "把零散工作整理成结果", "更新风险和下周动作"], ["提供周期、汇报对象和当期事实", "核验数字并区分事实与计划", "按固定结构输出简洁 Markdown"], ["根据这些工作记录写本周周报。", "把这份周报改成结果、风险、下周动作三部分。"], "仅使用用户提供并确认的当期工作事实和数字"),
    en: content("Weekly Report Writer", "Create or revise a concise Markdown weekly report structured as results, risks, and next-week actions", ["Write an individual or project weekly report", "Turn activity notes into outcomes", "Update risks and next actions"], ["Provide the period, audience, and current facts", "Verify numbers and separate facts from plans", "Return concise Markdown in the fixed structure"], ["Write this week's report from these work notes.", "Rewrite this report as results, risks, and next-week actions."], "Only current-period work facts and figures provided and confirmed by the user")
  },
  "zendesk-data": {
    zh: content("Zendesk 工单数据", "查询、导出和分析 Zendesk 工单、用户、组织及支持运营趋势", ["查询和统计 Zendesk 工单", "分析客户问题与支持趋势", "生成工单运营报表"], ["说明时间、状态、组织或指标范围", "使用受控账号查询并校验数据", "返回统计、明细或报告文件"], ["统计最近 7 天未解决的高优先级工单。", "分析本月最常见的客户问题并生成报表。"], "内置受控账号有权访问的 Zendesk 工单、用户、组织和分组数据"),
    en: content("Zendesk Ticket Data", "Query, export, and analyze Zendesk tickets, users, organizations, and support trends", ["Find and count Zendesk tickets", "Analyze customer issues and support trends", "Create ticket-operations reports"], ["Define time, status, organization, or metric scope", "Query and validate data with the controlled account", "Return statistics, details, or report files"], ["Count high-priority tickets unresolved in the past seven days.", "Analyze this month's most common customer issues and create a report."], "Zendesk tickets, users, organizations, and groups accessible to the bundled controlled account")
  },
  "baicells-country-opportunity-assessment": {
    zh: content("国家市场机会评估", "研究目标国家、移动市场与运营商，评估佰才邦产品适配、试点准备度和商业机会", ["调研国家通信市场和运营商", "评估产品与销售场景适配", "形成管理层结论和 ROI 工作簿"], ["提供国家、重点运营商和分析目标", "检索并登记市场、频谱、网络和商业证据", "完成适配评分、试点判断和决策材料"], ["评估印度尼西亚移动通信市场及重点运营商机会。", "为这个国家生成运营商分析、执行摘要和 ROI 工作簿。"], "可信公开来源、用户提供资料和获准访问的佰才邦产品资料；市场事实保留出处，商业价格不臆造"),
    en: content("Country Opportunity Assessment", "Research a country, mobile market, and operators to assess Baicells product fit, trial readiness, and commercial opportunity", ["Research a telecom market and its operators", "Assess product and sales-play fit", "Create an executive recommendation and ROI workbook"], ["Provide the country, priority operators, and decision goal", "Research and register market, spectrum, network, and commercial evidence", "Complete fit scoring, trial readiness, and decision deliverables"], ["Assess Indonesia's mobile market and its priority operators.", "Create an operator assessment, executive summary, and ROI workbook for this country."], "Credible public sources, user-provided material, and authorized Baicells product evidence; market claims remain sourced and commercial pricing is never invented")
  },
  "baicells-network-optimization-master": {
    zh: content("Baicells 网络优化大师", "构建和维护离线无线规划、参数核查、扇区地图与 KPI 质差诊断工具", ["开发无线规划和扇区地图", "核查 PCI、ZC 与邻区", "分析 KPI、告警和小区状态"], ["提供现有应用以及 LLD、OMC 或 KPI 数据", "校验字段与工程规则后修改对应模块", "完成离线、导出和真实数据回归验证"], ["基于这份 LLD 完善网络优化大师的 PCI 和邻区核查。", "导入这些 OMC 与 KPI 数据，生成综合质差诊断。"], "用户提供的 LLD、OMC、KPI、告警和小区状态文件以及脱敏应用资产；不会把项目数据固化进通用 Skill"),
    en: content("Baicells Network Optimization Master", "Build and maintain an offline tool for RF planning, parameter checks, sector maps, and KPI degradation diagnosis", ["Develop RF planning and sector mapping", "Check PCI, ZC, and neighbor relations", "Analyze KPIs, alarms, and cell status"], ["Provide the current app and LLD, OMC, or KPI data", "Validate fields and engineering rules before changing the target module", "Run offline, export, and real-data regression checks"], ["Improve PCI and neighbor checks in the optimization tool using this LLD.", "Import these OMC and KPI files and generate an integrated degradation diagnosis."], "User-provided LLD, OMC, KPI, alarm, and cell-status files plus sanitized app assets; project data is never embedded in the reusable Skill")
  },
  "create-b26-market-proposal": {
    zh: content("B26 市场推广提案", "制作一至两页、低投入且分阶段的 B26 项目前期商务提案或客户演示文稿", ["准备 B26 内部立项材料", "制作客户沟通提案", "说明样机、软件基线和后续 Cat-M 路径"], ["确认受众、语言和已知项目事实", "按三台样机与分阶段策略组织一至两页内容", "保留成本待补充项并检查产品承诺边界"], ["生成一页中文 B26 市场推广商务提案。", "为客户制作两页英文 B26 项目前期方案，所有成本保持待补充。"], "用户提供的项目事实、模板和演示资料；价格、资源投入、订单与交付承诺不会被臆造"),
    en: content("B26 Market-Entry Proposal", "Create a concise one- or two-slide B26 early-stage business proposal with low investment and phased risk control", ["Prepare an internal B26 review", "Create a customer discussion proposal", "Explain samples, software baseline, and the later Cat-M path"], ["Confirm audience, language, and supplied project facts", "Structure one or two slides around three samples and phased investment", "Keep costs pending and verify product-commitment boundaries"], ["Create a one-slide Chinese B26 market-entry proposal.", "Prepare a two-slide English customer proposal and leave every cost field pending."], "User-provided project facts, templates, and presentation material; prices, resource effort, orders, and delivery commitments are never invented")
  },
  "create-box-no-xlsx": {
    zh: content("箱号列表 XLSX", "把箱号列表按原顺序整理为首列固定为 BOX_NO 的文本型 XLSX 文件", ["把箱号列表转成 Excel", "保留前导零和长数字", "生成可筛选的 BOX_NO 清单"], ["粘贴或上传箱号列表", "清理空行并按文本保留原值和顺序", "生成、校验并交付单列表格"], ["把这些箱号生成 BOX_NO Excel。", "按原顺序整理这批箱号，保留前导零和重复项。"], "仅使用用户提供的箱号列表和本任务生成的 XLSX；默认不去重、不排序"),
    en: content("Box Number XLSX", "Turn a box-number list into a text-safe XLSX whose first column is fixed as BOX_NO", ["Convert box numbers to Excel", "Preserve leading zeros and long values", "Create a filterable BOX_NO list"], ["Paste or upload the box-number list", "Remove blank items while preserving text and order", "Generate, validate, and deliver the single-column workbook"], ["Create a BOX_NO workbook from these box numbers.", "Keep the original order, leading zeros, and duplicate box numbers."], "Only the user-provided box-number list and the generated XLSX; values are not deduplicated or sorted unless requested")
  },
  "generate-cpe-rework-sql": {
    zh: content("CPE 返工 SQL 生成器", "从图片或列表提取 BRDSN，并生成默认回滚、带事务校验的 MC2 返工 SQL", ["从截图提取 CPE BRDSN", "批量生成返工更新脚本", "校验号码格式和重复项"], ["提供图片、文本或表格中的 BRDSN", "逐项复核格式、模糊字符和重复号码", "生成默认回滚的 SQL 文件并核验影响条件"], ["从这张图片提取 BRDSN 并生成 MC2 返工 SQL。", "校验这批号码后生成默认不提交的返工脚本。"], "仅使用用户提供的号码和图片；只生成 SQL 文件，不连接或执行生产数据库"),
    en: content("CPE Rework SQL Generator", "Extract BRDSNs from images or lists and create transaction-guarded MC2 rework SQL that rolls back by default", ["Extract CPE BRDSNs from screenshots", "Generate a batch rework script", "Validate number format and duplicates"], ["Provide BRDSNs in an image, text, or spreadsheet", "Review format, ambiguous characters, and duplicates", "Generate the rollback-by-default SQL and verify all update guards"], ["Extract the BRDSNs from this image and create the MC2 rework SQL.", "Validate these numbers and generate a rework script that does not commit by default."], "Only user-provided numbers and images; generates a SQL file but never connects to or executes against production databases")
  },
  "parse-test-logs-to-xlsx": {
    zh: content("TXT 测试日志转 Excel", "从多个 TXT 或 LOG 中提取测试字段，生成可筛选且保留文件与行号的 XLSX 记录表", ["汇总多个测试日志", "提取机型、流程、指令和工单", "整理无法确认的日志字段"], ["上传需要解析的 TXT 或 LOG", "识别编码、上下文和测试事件并保留来源行号", "生成日志记录与待确认两个工作表并校验"], ["解析这些测试 LOG 并生成测试记录 Excel。", "汇总多个 TXT，提取机型、流程、命令、返回和工单号。"], "仅只读处理用户上传的文本日志并生成 XLSX；不修改源文件，不猜测无法确认字段"),
    en: content("Test Logs to Excel", "Extract test fields from TXT or LOG files into a filterable XLSX with source files and line numbers retained", ["Consolidate multiple test logs", "Extract model, process, command, and work order", "Track fields that need confirmation"], ["Upload the TXT or LOG files", "Detect encoding, context, and test events while retaining source lines", "Generate and validate Records and Needs Confirmation sheets"], ["Parse these test logs and create a test-record workbook.", "Consolidate these TXT files and extract models, processes, commands, responses, and work orders."], "Read-only processing of user-uploaded text logs and generated XLSX files; source files are unchanged and uncertain fields are not guessed")
  },
  "recreate-image-as-pdf": {
    zh: content("按图复刻 PDF", "根据参考图片生成物理尺寸准确、版式一致并经过渲染检查的可打印 PDF", ["把标签或铭牌图片转为 PDF", "按标注尺寸复刻单页版式", "重建文字、线框和机器码区域"], ["提供参考图和目标物理尺寸", "识别成品边界并选择整图嵌入或矢量重建", "校验页面尺寸并渲染对比后交付"], ["按这张标签图复刻一份 110×120 mm 的 PDF。", "把这个扫描件重建为清晰可打印的单页 PDF。"], "用户提供的参考图片、尺寸和替换文本以及本任务生成的 PDF；不臆造无法识别的条码或二维码内容"),
    en: content("Recreate Image as PDF", "Rebuild a reference image as a print-ready PDF with accurate physical size, matching layout, and rendered verification", ["Convert a label or nameplate image to PDF", "Recreate a one-page layout at marked dimensions", "Rebuild text, rules, and machine-code areas"], ["Provide the reference image and target physical size", "Identify the finished boundary and choose image embedding or vector rebuilding", "Verify page dimensions and compare the rendered PDF before delivery"], ["Recreate this label as a 110 by 120 mm PDF.", "Rebuild this scan as a clean, printable single-page PDF."], "User-provided images, dimensions, and replacement text plus generated PDFs; unreadable barcode or QR content is never invented")
  },
  "tp-generator": {
    zh: content("端到端技术方案生成器", "通过渐进问答澄清场景和网元范围，生成面向客户的佰才邦 4G/5G 技术方案", ["从零编写技术方案或 TP", "把 RFP 转成端到端解决方案", "补充和修订已有客户方案"], ["提供项目描述、RFP 或已有方案", "先确认应用场景和各网元纳入范围，再逐轮补齐关键需求", "核验产品证据并生成客户版文档"], ["为这个 FWA 项目生成一份英文端到端技术方案。", "根据这份 RFP 逐步澄清需求，然后生成客户版 TP。"], "用户输入、上传的 RFP 和获准访问的佰才邦知识库资料；未证实的产品能力、数量和接口保留为待确认"),
    en: content("End-to-End Technical Proposal", "Use progressive clarification to confirm the scenario and network-element scope, then create a customer-ready Baicells 4G/5G proposal", ["Create a technical proposal from scratch", "Turn an RFP into an end-to-end solution", "Update an existing customer proposal"], ["Provide the project description, RFP, or current proposal", "Confirm the application scenario and included network domains before closing critical gaps", "Validate product evidence and generate the customer document"], ["Create an English end-to-end technical proposal for this FWA project.", "Clarify this RFP progressively, then generate a customer-ready TP."], "User input, uploaded RFPs, and authorized Baicells knowledge-base material; unsupported capabilities, quantities, and interfaces remain to be confirmed")
  },
  "use-cpe-manufacturing-db-schema": {
    zh: content("CPE 制造数据库表结构", "使用已记录的 SQL Server 表结构回答字段问题、编写查询并排查 CPE 制造数据", ["查询制造数据库表和字段", "编写或审查 SQL Server 查询", "分析测试、配置、打印与包装记录"], ["说明要查询的业务对象和结果", "读取已记录的表结构并区分结构事实与业务推断", "生成带字段和类型约束的 T-SQL 或排查建议"], ["根据已记录表结构查询这个 SN 的包装信息。", "检查这段 CPE_TEST_RESULT SQL 是否符合字段类型。"], "Skill 内记录的 CPE 制造数据库 DDL 以及用户提供的 SQL 或样例；不自动连接数据库，也不假设未记录的键和约束"),
    en: content("CPE Manufacturing DB Schema", "Use the recorded SQL Server schema to answer field questions, write queries, and troubleshoot CPE manufacturing data", ["Look up manufacturing tables and fields", "Write or review SQL Server queries", "Analyze test, configuration, printing, and packing records"], ["Describe the business object and required result", "Read the recorded schema and separate schema facts from inferred meaning", "Create type-aware T-SQL or troubleshooting guidance"], ["Use the recorded schema to find packing data for this serial number.", "Check whether this CPE_TEST_RESULT query matches the recorded field types."], "The recorded CPE manufacturing DDL plus user-provided SQL or samples; does not automatically connect to a database or assume unrecorded keys and constraints")
  },
  "winforms-device-tool-maintainer": {
    zh: content("WinForms 设备工具维护", "诊断和修复 C# 设备控制工具的界面卡顿、取消失效与设备安全停止问题", ["排查 WinForms 界面冻结", "改造阻塞式设备采集流程", "修复停止、清理和发布流程"], ["提供项目代码和可复现操作路径", "审计 UI 线程、原生调用、并发和取消链路", "完成 Release 构建并列出真实设备验收边界"], ["排查这个 WinForms 设备工具运行采集后界面卡死的问题。", "修复 Stop 按钮无响应，并确保异常时停止发射和清理设备。"], "用户提供的 C# 项目、构建输出和日志；没有真实设备时不会声称完成硬件验收"),
    en: content("WinForms Device Tool Maintenance", "Diagnose and fix UI freezes, failed cancellation, and unsafe device shutdown in C# device-control tools", ["Investigate a frozen WinForms UI", "Refactor blocking device acquisition", "Fix stop, cleanup, and release workflows"], ["Provide the project and reproducible operation path", "Audit UI-thread work, native calls, serialization, and cancellation", "Build Release and document the remaining real-device acceptance boundary"], ["Diagnose why this WinForms device tool freezes during acquisition.", "Fix the unresponsive Stop button and ensure the transmitter is stopped on failure."], "User-provided C# projects, build output, and logs; physical hardware acceptance is never claimed without the real equipment")
  },
  "megrez-rf-planning": {
    zh: content("Megrez RF 规划与仿真", "查询 Megrez 工程、运行异步 Sionna RT 覆盖仿真并返回覆盖统计和交互式 3D 链接", ["查看当前 RF 工程", "提交并监控覆盖仿真", "比较覆盖统计和 3D 结果"], ["说明目标工程、分辨率和覆盖阈值", "通过受控 API 提交任务并按 job_id 等待", "返回真实统计、只读工程链接和 3D 结果链接"], ["查询当前 RF 工程并运行一次覆盖仿真。", "用 0.5 米分辨率仿真并返回覆盖率和 3D 结果链接。"], "当前账号获准访问的 Megrez 工程、仿真任务和结果链接；修改发射机参数或删除站点前需确认"),
    en: content("Megrez RF Planning & Simulation", "Inspect Megrez projects, run asynchronous Sionna RT coverage simulations, and return statistics with interactive 3D links", ["Inspect the active RF project", "Submit and monitor a coverage simulation", "Compare coverage statistics and 3D results"], ["Specify the project, resolution, and coverage threshold", "Submit through the controlled API and wait using the returned job ID", "Return actual statistics, read-only project link, and 3D result link"], ["Inspect the active RF project and run a coverage simulation.", "Simulate at 0.5-meter resolution and return coverage statistics and the 3D result link."], "Megrez projects, simulation jobs, and result links authorized for the current account; transmitter changes or site deletion require confirmation")
  },
  "plugin-creator": {
    zh: content("插件创建助手", "创建或更新符合规范的 Codex 插件目录、manifest 和个人插件市场条目", ["创建新的个人插件", "补充插件中的 Skill 或可选目录", "更新插件市场排序和可用性信息"], ["说明插件名称和需要包含的能力", "生成目录与 .codex-plugin/plugin.json", "校验 manifest，并按需要更新市场与重装缓存"], ["创建一个包含两个 Skill 的个人插件。", "为这个插件补充 marketplace 条目并校验结构。"], "用户指定的本地插件目录和个人 marketplace 配置；创建或更新文件前遵循目标路径权限"),
    en: content("Plugin Creator", "Create or update valid Codex plugin directories, manifests, and personal marketplace entries", ["Create a personal plugin", "Add Skills or optional plugin folders", "Update marketplace ordering and availability metadata"], ["Specify the plugin name and included capabilities", "Generate the directory and .codex-plugin/plugin.json", "Validate the manifest and update marketplace or reinstall cache when needed"], ["Create a personal plugin containing two Skills.", "Add a marketplace entry for this plugin and validate its structure."], "User-specified local plugin directories and personal marketplace configuration, subject to target-path permissions")
  },
  "skill-installer": {
    zh: content("Skill 安装助手", "从精选目录或 Git 仓库安装 Codex Skill 到当前运行环境", ["查看可安装 Skill", "安装精选 Skill", "从公开或私有仓库安装 Skill"], ["说明要安装的 Skill 或仓库路径", "检查来源、目标名称和现有安装", "安装到 CODEX_HOME 并提示重新加载"], ["列出当前可安装的精选 Skill。", "从这个 Git 仓库安装指定 Skill。"], "所选目录或 Git 仓库以及当前 CODEX_HOME/skills；安装会写入当前运行环境"),
    en: content("Skill Installer", "Install Codex Skills from the curated catalog or a Git repository into the current runtime", ["List installable Skills", "Install a curated Skill", "Install a Skill from a public or private repository"], ["Specify the Skill or repository path", "Check source, target name, and existing installation", "Install into CODEX_HOME and prompt for reload"], ["List the curated Skills available to install.", "Install the specified Skill from this Git repository."], "The selected catalog or Git repository and current CODEX_HOME/skills; installation writes to the current runtime")
  }
};

export const NATIVE_PRESENTATION_BACKFILL_NAMES = [
  "oxm-operations",
  "plugin-creator",
  "skill-installer"
] as const;
